name: Pre-Release created
on:
  release:
    types: [created, edited]
jobs:
  pre-release:
    if: (github.event.release.prerelease || !github.event.release.prerelease)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: .github/config/configuration.json
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOK }}
      - name: Get last pre-release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
      - name: Update last Pre-release
        uses: kaliber5/action-update-release@v1
        with:
          token: ${{ secrets.GIT_TOK }}
          id: ${{ steps.latest_release.outputs.id }}
          body: ${{ steps.github_release.outputs.changelog }}
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: |
          PATCH_STR='version'
          if [[ "$pre_release" =~ .*"$PATCH_STR".* ]]; then
            PRE_TAG=`echo $pre_release | sed 's/version-//'`
            PRE_RELEASE_TAG=rc-`echo $PRE_TAG`
            echo 'Update current TAG'
            echo $PRE_RELEASE_TAG
          else
            echo 'Dont apply any change'
            PRE_RELEASE_TAG=$pre_release
          fi
          
          COMMIT_BASE=$(git merge-base $MERGE_BASE $pre_release)
          echo $COMMIT_BASE
          CHANGES=`git diff --name-only "$COMMIT_BASE^!" -- . ':!images' | wc -l`
          echo $CHANGES
          if [ $CHANGES -gt  0 ]
          then     
          echo "Congratulations it's all ok"        
          else
          echo "- Nothing to do in Core"
          fi                     
          echo $PRE_RELEASE_TAG
          echo "This is a test to Exec an action from prerelease"
        env:
          pre_release: ${{ github.event.release.tag_name }}
          MERGE_BASE: origin/master
