name: Pre-Release created
on:
  release:
    types: [created]
jobs:
  pre-release:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.GIT_TOK }}
          submodules: recursive
          fetch-depth: 0
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOK }}         
      - name: Update last Pre-release
        uses: kaliber5/action-update-release@v1
        with:
          token: ${{ secrets.GIT_TOK }}
          id: ${{ github.event.release.tag_name }}
          name: Version ${{ github.event.release.tag_name }}
          tag_name: ${{ github.event.release.tag_name }}
          body: |
            ${{ steps.github_release.outputs.changelog }}
      - uses: actions/checkout@master
      - run: |
          echo $pre_release
          echo "This is a test to Exec an action from prerelease"
        env:
          pre_release: ${{ github.event.release.tag_name }}
