name: Publish TechDocs Site

on:
  push:
    branches: [master]

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    env:
      TECHDOCS_CONTAINER_NAME: ${{ secrets.TECHDOCS_CONTAINER_NAME }}
      TECHDOCS_STORAGE_ACCOUNT: ${{ secrets.TECHDOCS_STORAGE_ACCOUNT }}
      TECHDOCS_STORAGE_SECRET: ${{ secrets.TECHDOCS_STORAGE_SECRET }}
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'devops-exercise'
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2

      - name: Install techdocs-cli
        run: sudo npm install -g @techdocs/cli

      - name: Install mkdocs and mkdocs plugins
        run: python -m pip install mkdocs-techdocs-core==0.*

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose

      - name: Publish docs site
        run:
          techdocs-cli publish --publisher-type azureBlobStorage --azureAccountName $TECHDOCS_STORAGE_ACCOUNT --azureAccountKey $TECHDOCS_STORAGE_SECRET --storage-name $TECHDOCS_CONTAINER_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME